- lib/ledger_sync/adaptors/quickbooks_online/customer/searcher.rb
- lib/ledger_sync/adaptors/quickbooks_online/searcher.rb
- spec/adaptors/quickbooks_online/searcher_spec.rb
> DRY up QBO searchers

- lib/ledger_sync/resource.rb
- lib/ledger_sync/resource_attribute.rb
- lib/ledger_sync/resource_attribute/mixin.rb
- lib/ledger_sync/resource_attribute/reference/many.rb
- lib/ledger_sync/resource_attribute/reference/one.rb
- lib/ledger_sync/util/resources_builder.rb
- spec/adaptors/operation_contract_spec.rb
- spec/resources/dirty_spec.rb
- spec/serializable/operation_spec.rb
- spec/serializable/resource_spec.rb
- spec/serializable/result_spec.rb
> Fix dirty changes

- lib/ledger_sync.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/create.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/find.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/update.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/searcher.rb
- lib/ledger_sync/resources/deposit.rb
- lib/ledger_sync/resources/deposit_line_item.rb
- spec/adaptors/quickbooks_online/operations/deposit/create_spec.rb
- spec/adaptors/quickbooks_online/operations/deposit/find_spec.rb
- spec/adaptors/quickbooks_online/operations/deposit/update_spec.rb
- spec/integrations/quickbooks_online/deposits/create_spec.rb
- spec/integrations/quickbooks_online/deposits/find_spec.rb
- spec/integrations/quickbooks_online/deposits/update_spec.rb
- spec/support/input_helpers.rb
- spec/support/quickbooks_helpers.rb
> Add Deposit resource and Operations

- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
- spec/adaptors/quickbooks_online/adaptor_spec.rb
- spec/integrations/quickbooks_online/accounts/create_spec.rb
- spec/integrations/quickbooks_online/accounts/find_spec.rb
- spec/integrations/quickbooks_online/accounts/searcher_spec.rb
- spec/integrations/quickbooks_online/accounts/update_spec.rb
- spec/integrations/quickbooks_online/adaptor_spec.rb
- spec/integrations/quickbooks_online/customers/create_spec.rb
- spec/integrations/quickbooks_online/customers/find_spec.rb
- spec/integrations/quickbooks_online/customers/searcher_spec.rb
- spec/integrations/quickbooks_online/customers/update_spec.rb
- spec/integrations/quickbooks_online/deposits/create_spec.rb
- spec/integrations/quickbooks_online/deposits/find_spec.rb
- spec/integrations/quickbooks_online/deposits/update_spec.rb
- spec/integrations/quickbooks_online/expenses/create_spec.rb
- spec/integrations/quickbooks_online/expenses/find_spec.rb
- spec/integrations/quickbooks_online/expenses/update_spec.rb
- spec/integrations/quickbooks_online/payments/create_spec.rb
- spec/integrations/quickbooks_online/payments/find_spec.rb
- spec/integrations/quickbooks_online/payments/update_spec.rb
- spec/integrations/quickbooks_online/vendors/create_spec.rb
- spec/integrations/quickbooks_online/vendors/find_spec.rb
- spec/integrations/quickbooks_online/vendors/searcher_spec.rb
- spec/integrations/quickbooks_online/vendors/update_spec.rb
- spec/support/quickbooks_helpers.rb
Fix https://github.com/LedgerSync/ledger_sync/issues/48
> Add refresh_token_expires_at to adaptor and attributes to save

- lib/ledger_sync.rb
- lib/ledger_sync/adaptors/quickbooks_online/bill/operations/create.rb
- lib/ledger_sync/adaptors/quickbooks_online/bill/operations/find.rb
- lib/ledger_sync/adaptors/quickbooks_online/bill/operations/update.rb
- lib/ledger_sync/adaptors/quickbooks_online/bill/searcher.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/create.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/update.rb
- lib/ledger_sync/adaptors/quickbooks_online/expense/operations/create.rb
- lib/ledger_sync/adaptors/quickbooks_online/expense/operations/update.rb
- lib/ledger_sync/adaptors/test/expense/operations/create.rb
- lib/ledger_sync/adaptors/test/expense/operations/update.rb
- lib/ledger_sync/resources/bill.rb
- lib/ledger_sync/resources/bill_line_item.rb
- spec/adaptors/quickbooks_online/operations/bill/create_spec.rb
- spec/adaptors/quickbooks_online/operations/bill/find_spec.rb
- spec/adaptors/quickbooks_online/operations/bill/update_spec.rb
- spec/integrations/quickbooks_online/bills/create_spec.rb
- spec/integrations/quickbooks_online/bills/find_spec.rb
- spec/integrations/quickbooks_online/bills/update_spec.rb
- spec/support/input_helpers.rb
- spec/support/quickbooks_helpers.rb
> Add Bill resource and operations

- lib/ledger_sync/adaptors/quickbooks_online/vendor/operations/create.rb
- lib/ledger_sync/adaptors/quickbooks_online/vendor/operations/find.rb
- lib/ledger_sync/adaptors/quickbooks_online/vendor/operations/update.rb
- lib/ledger_sync/adaptors/quickbooks_online/vendor/searcher.rb
- lib/ledger_sync/adaptors/test/vendor/operations/create.rb
- lib/ledger_sync/adaptors/test/vendor/operations/find.rb
- lib/ledger_sync/adaptors/test/vendor/operations/invalid.rb
- lib/ledger_sync/adaptors/test/vendor/operations/update.rb
- lib/ledger_sync/adaptors/test/vendor/operations/valid.rb
- lib/ledger_sync/adaptors/test/vendor/searcher.rb
- lib/ledger_sync/resources/vendor.rb
- spec/adaptors/quickbooks_online/operations/vendor/create_spec.rb
- spec/adaptors/quickbooks_online/operations/vendor/find_spec.rb
- spec/adaptors/quickbooks_online/operations/vendor/update_spec.rb
- spec/adaptors/test/operations/vendor/create_spec.rb
- spec/adaptors/test/operations/vendor/find_spec.rb
- spec/adaptors/test/operations/vendor/update_spec.rb
- spec/support/input_helpers.rb
- spec/support/quickbooks_helpers.rb
> Add DisplayName to Vendor

- lib/ledger_sync.rb
- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
- lib/ledger_sync/adaptors/quickbooks_online/journal_entry/mapping.rb
- lib/ledger_sync/adaptors/quickbooks_online/journal_entry/operations/create.rb
- lib/ledger_sync/adaptors/quickbooks_online/journal_entry/operations/find.rb
- lib/ledger_sync/adaptors/quickbooks_online/journal_entry/operations/update.rb
- lib/ledger_sync/adaptors/quickbooks_online/journal_entry/searcher.rb
- lib/ledger_sync/resources/journal_entry.rb
- lib/ledger_sync/resources/journal_entry_line_item.rb
- spec/adaptors/quickbooks_online/operations/journal_entry/create_spec.rb
- spec/adaptors/quickbooks_online/operations/journal_entry/find_spec.rb
- spec/adaptors/quickbooks_online/operations/journal_entry/update_spec.rb
- spec/integrations/quickbooks_online/journal_entries/create_spec.rb
- spec/integrations/quickbooks_online/journal_entries/find_spec.rb
- spec/integrations/quickbooks_online/journal_entries/update_spec.rb
- spec/support/input_helpers.rb
- spec/support/quickbooks_helpers.rb
> Add JournalEntry resource and operations

- spec/support/quickbooks_helpers.rb
This will be a hotpatch for 1.1.1
@mattgmarcus we will need to bump versions for the next release
> Fix stubbing

- lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer.rb
- lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer_type/account_type.rb
- spec/integrations/quickbooks_online/accounts/create_spec.rb
- spec/support/quickbooks_helpers.rb
Fix #86
@mattgmarcus Can you verify that this works as expected?
> Auto populate classification if missing

- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
- lib/ledger_sync/adaptors/quickbooks_online/ledger_serializer_type/account_sub_type.rb
- lib/ledger_sync/resources/account.rb
- spec/adaptors/quickbooks_online/account/ledger_serializer_spec.rb
Fix https://github.com/LedgerSync/ledger_sync/issues/58
> Add oauth helpers for connecting QBO and exchanging code for tokens

- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
- spec/adaptors/quickbooks_online/adaptor_spec.rb
> Add url helper for QBO

- README.md
- release.sh
Fixes https://github.com/LedgerSync/ledger_sync/issues/90
> Update release script and document

- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
- spec/adaptors/quickbooks_online/adaptor_spec.rb
- spec/support/quickbooks_helpers.rb
Fixes https://github.com/LedgerSync/ledger_sync/issues/82
> Add method to revoke qbo access token

- README.md
- lib/ledger_sync/adaptors/adaptor.rb
- lib/ledger_sync/adaptors/quickbooks_online/webhook.rb
- lib/ledger_sync/adaptors/quickbooks_online/webhook_event.rb
- lib/ledger_sync/adaptors/quickbooks_online/webhook_notification.rb
- lib/ledger_sync/resource.rb
- spec/adaptors/quickbooks_online/shared_examples.rb
- spec/adaptors/quickbooks_online/webhook_event_spec.rb
- spec/adaptors/quickbooks_online/webhook_notification_spec.rb
- spec/adaptors/quickbooks_online/webhook_spec.rb
- spec/support/quickbooks_helpers.rb
Fixes https://github.com/LedgerSync/ledger_sync/issues/66
See the updated readme for how to use.  Let me know if it isn't clear.
> Adds webhook parsing for QBO

- README.md
- lib/ledger_sync.rb
- lib/ledger_sync/adaptor_configuration.rb
- lib/ledger_sync/adaptor_configuration_store.rb
- lib/ledger_sync/adaptors/quickbooks_online/config.rb
- lib/ledger_sync/adaptors/quickbooks_online/operation.rb
- lib/ledger_sync/adaptors/test/config.rb
- lib/ledger_sync/resources/customer.rb
- lib/ledger_sync/util/string_helpers.rb
- qa.rb
- qa/quickbooks_online_test.rb
- qa/test.rb
- spec/adaptors/quickbooks_online/adaptor_spec.rb
- spec/serializable/adaptor_spec.rb
I ripped out the useful pieces of PR #99 so that we could use them without having to merge in NetSuite until it's ready.
> Update lib to better handle multiple adaptors

- Gemfile.lock
- README.md
- ledger_sync.gemspec
- lib/ledger_sync.rb
- lib/ledger_sync/adaptor_configuration.rb
- lib/ledger_sync/adaptor_configuration_store.rb
- lib/ledger_sync/adaptors/quickbooks_online/config.rb
- lib/ledger_sync/adaptors/quickbooks_online/operation.rb
- lib/ledger_sync/adaptors/stripe/adaptor.rb
- lib/ledger_sync/adaptors/stripe/config.rb
- lib/ledger_sync/adaptors/stripe/customer/operations/create.rb
- lib/ledger_sync/adaptors/stripe/customer/operations/find.rb
- lib/ledger_sync/adaptors/stripe/operation.rb
- lib/ledger_sync/adaptors/stripe/operation/create.rb
- lib/ledger_sync/adaptors/stripe/operation/find.rb
- lib/ledger_sync/adaptors/stripe/operation/full_update.rb
- lib/ledger_sync/adaptors/stripe/operation/sparse_update.rb
- lib/ledger_sync/adaptors/test/config.rb
- lib/ledger_sync/resources/customer.rb
- lib/ledger_sync/util/string_helpers.rb
- qa.rb
- qa/quickbooks_online_test.rb
- qa/stripe_test.rb
- qa/test.rb
- spec/adaptors/quickbooks_online/adaptor_spec.rb
- spec/integrations/stripe/adaptor_spec.rb
- spec/integrations/stripe/customers/create_spec.rb
- spec/integrations/stripe/customers/find_spec.rb
- spec/serializable/adaptor_spec.rb
- spec/support/stripe_helpers.rb
Depends on #100
@mattgmarcus @jozefvaclavik For launch, I wanted to have a second working adaptor.  I figured this was a decent example of the ease of adding one but also how it can be an "atypical" ledger.
Thoughts?
> Add Stripe Adaptor

- spec/integrations/netsuite/customers/create_spec.rb
- spec/integrations/netsuite/subsidiaries/create_spec.rb
- spec/spec_helper.rb
@jozefvaclavik I probably prefer this, where we have to explicitly enable VCR as needed.
Thoughts?  If good, just merge, and I'll incorporate in my existing PRs.
> Add explicit vcr enablement

- lib/ledger_sync/adaptors/netsuite/adaptor.rb
- lib/ledger_sync/adaptors/netsuite/record/metadata.rb
> Add a helper method for creating an adaptor from ENV

- lib/ledger_sync.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/ledger_serializer.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/create.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/find.rb
- lib/ledger_sync/adaptors/quickbooks_online/deposit/operations/update.rb
- lib/ledger_sync/resources/deposit.rb
- spec/adaptors/quickbooks_online/operations/deposit/create_spec.rb
- spec/adaptors/quickbooks_online/operations/deposit/find_spec.rb
- spec/adaptors/quickbooks_online/operations/deposit/update_spec.rb
- spec/support/input_helpers.rb
- spec/support/quickbooks_online_helpers.rb
Adds Department reference to Deposit resource
> Add Department to Deposit

- spec/adaptors/quickbooks_online/request_spec.rb
- spec/support/quickbooks_online_helpers.rb
Fixes broken specs due to bumped faraday gem version
> Bump faraday version on stubbed requests

- lib/ledger_sync/adaptors/mixins/infer_ledger_serializer_mixin.rb
- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
- lib/ledger_sync/adaptors/quickbooks_online/request.rb
- spec/adaptors/quickbooks_online/operation_spec.rb
- spec/support/quickbooks_online_helpers.rb
- spec/support/test_adaptor_helpers.rb
> Fix memoizing issue

- lib/ledger_sync/adaptors/netsuite/account/operations/create.rb
- lib/ledger_sync/adaptors/netsuite/currency/operations/create.rb
- lib/ledger_sync/adaptors/netsuite/customer/operations/create.rb
- lib/ledger_sync/adaptors/netsuite/department/operations/create.rb
- lib/ledger_sync/adaptors/netsuite/vendor/operations/create.rb
> Fix dry validations

- lib/ledger_sync/adaptors/adaptor.rb
- lib/ledger_sync/adaptors/netsuite/account/searcher.rb
- lib/ledger_sync/adaptors/netsuite/department/searcher.rb
- lib/ledger_sync/adaptors/netsuite/searcher.rb
- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
- lib/ledger_sync/adaptors/searcher.rb
Fix #168 
Now it's way easier to add a simple searcher in NS.  Thoughts?
> DRY up NetSuite searchers and ledger resource overrides

- README.md
- lib/ledger_sync/adaptor_configuration.rb
- lib/ledger_sync/adaptor_configuration_store.rb
- lib/ledger_sync/adaptors/adaptor.rb
- lib/ledger_sync/adaptors/operation.rb
- lib/ledger_sync/adaptors/quickbooks_online/util/adaptor_error_parser.rb
- lib/ledger_sync/adaptors/quickbooks_online/util/error_matcher.rb
- lib/ledger_sync/adaptors/quickbooks_online/util/error_parser.rb
- lib/ledger_sync/adaptors/quickbooks_online/util/operation_error_parser.rb
- lib/ledger_sync/error/adaptor_errors.rb
- lib/ledger_sync/resource.rb
- spec/adaptors/adaptor_spec.rb
- spec/adaptors/configuration_spec.rb
- spec/adaptors/operation_contract_spec.rb
- spec/adaptors/quickbooks_online/util/error_matcher_spec.rb
- spec/qa/support/adaptor_support_qa_setup.rb
- spec/qa/support/quickbooks_online_helpers.rb
- spec/serializable/adaptor_spec.rb
- spec/util/read_only_object_spec.rb
This is just a refactor to use more descriptive names using `class` (e.g. `LedgerClass` over `Klass`).
> Follow convention of descriptive use of class over klass

- spec/support/netsuite/records/account.json
- spec/support/netsuite/records/currency.json
- spec/support/netsuite/records/customer.json
- spec/support/netsuite/records/department.json
- spec/support/netsuite/records/location.json
- spec/support/netsuite_helpers.rb
Just moved the JSON out to a cleaner format, as the helper file was becoming unwieldy.
> Separate rspec netsuite json for easier editing

- lib/ledger_sync/adaptors/operation.rb
- spec/adaptors/netsuite/location/create_spec.rb
- spec/support/netsuite/shared_examples.rb
I'm not a fan of "automagic," but I'm OK with it in tests given that it makes them easier to write (aka just a few lines).
If approved, I can go through and actually DRY up the existing specs.  But everything should still work as it's just decomposed.
> DRY up netsuite operation tests

- lib/ledger_sync/adaptors/netsuite/record/http_method.rb
- lib/ledger_sync/adaptors/netsuite/record/metadata.rb
There was a bug with the method helpers.  This fixes those and the key store for http_methods
> Fix method retrieval

- README.md
- bin/quickbooks_online_oauth_server.rb
- lib/ledger_sync/adaptors/quickbooks_online/adaptor.rb
> Add utility for more easily retrieving QBO access tokens

- .travis.yml
- lib/ledger_sync/adaptors/ledger_serializer_type/references_one_type.rb
- lib/ledger_sync/adaptors/netsuite/ledger_serializer.rb
- lib/ledger_sync/type/boolean.rb
- lib/ledger_sync/type/float.rb
- lib/ledger_sync/type/hash.rb
- lib/ledger_sync/type/integer.rb
- lib/ledger_sync/type/reference_many.rb
- lib/ledger_sync/type/reference_one.rb
- lib/ledger_sync/type/string.rb
To ensure compatibility, I wanted to test more ruby versions.  I was not sure where to find the definitive list of latest stable/supported ruby versions.  Hmu if you know.
> Test multiple ruby versions

- lib/ledger_sync/ledgers/quickbooks_online/department/deserializer.rb
- spec/qa/netsuite/account_spec.rb
- spec/qa/netsuite/check_spec.rb
- spec/qa/netsuite/currency_spec.rb
- spec/qa/netsuite/customer_deposit_spec.rb
- spec/qa/netsuite/customer_spec.rb
- spec/qa/netsuite/department_spec.rb
- spec/qa/netsuite/ledger_class_spec.rb
- spec/qa/netsuite/location_spec.rb
- spec/qa/netsuite/vendor_spec.rb
- spec/qa/netsuite_soap/customer_spec.rb
- spec/qa/support/netsuite_helpers.rb
- spec/qa/support/netsuite_soap_helpers.rb
Our QA specs have been broken since our recent directory renaming. This PR fixes all broken QA specs.
> Fix Broken QA Specs

- lib/ledger_sync/ledgers/quickbooks_online/expense/deserializer.rb
- lib/ledger_sync/ledgers/quickbooks_online/resources/customer.rb
- spec/ledgers/quickbooks_online/expense/deserializer_spec.rb
This was breaking when referencing a customer on a QBO expense and deposit
> Add name to QBO Customer

- lib/ledger_sync/ledgers/netsuite/check_line_item/deserializer.rb
- lib/ledger_sync/ledgers/netsuite/check_line_item/serializer.rb
- spec/ledgers/netsuite/check_line_item/deserializer_spec.rb
- spec/ledgers/netsuite/check_line_item/serializer_spec.rb
Reopened as a feature instead of https://github.com/LedgerSync/ledger_sync/pull/254
> Fix class - ledger_class mapping

- .github/workflows/gem-workflow.yml
- .rubocop.yml
- ledger_sync.gemspec
- lib/ledger_sync/version.rb
- spec/deserializer_spec.rb
Why
- To update github actions
- To update version logic
- Adding deserializer test
> Config/ci  GitHub actions

- lib/ledger_sync/util/dotenv_updator.rb
Don't read from .local.env if it doesn't exist
> Fix exception thrown on startup (missing .local.env file)

- Dockerfile
- docker-compose.yml
Hello 👋, thanks for your hard work making & maintaining this gem.
I created a small PR because your docker setup was not working.
Fixes:
- Docker image failing to build because bundler was missing
- Docker container shutting down instantly after startup
> Fix docker setup

- .github/workflows/codeql.yml
> [FDN-1796] Create codeql.yml

- .github/workflows/codeql.yml
> Develop to Master

- .github/workflows/codeql.yml
- Gemfile.lock
- ledger_sync.gemspec
> feat: update openssl 3
